export const projects = [
  {
    no: '01',
    title: 'Bismarck Hunt',
    subtitle: '兵棋 AI 演化框架',
    enSubtitle: 'Evolutionary Wargame AI',
    period: '2026',
    tags: ['React 19', 'TypeScript', 'C++', 'PyTorch', 'MAP-Elites'],
    metric: '~500/s',
    metricLabel: 'C++ 并发对局',
    enMetricLabel: 'C++ simulated matches',
    copy: '将经典隐藏移动兵棋完整电子化，再把它变成可大规模训练的 AI 环境。游戏规则、可视化、并发模拟与模型训练形成一条闭环。',
    enCopy: 'A full digital adaptation of a hidden-movement naval wargame, extended into a scalable AI training environment.',
    details: ['42 格六角地图，德军 2 舰对英军 11 舰与 4 个伪装算子，覆盖移动、索敌、战斗和 18 回合胜负规则。', 'C++ 多线程引擎约 500 局/秒；双种群共演化结合 MAP-Elites，保留不同战术风格。', 'V4 Patrol 策略消融实验让英军胜率提升 18%；1,000 局试生产生成 238,502 个训练样本。'],
    enDetails: ['A 42-hex map with complete movement, search, combat and 18-turn victory rules.', 'A multithreaded C++ engine runs roughly 500 matches per second with co-evolution and MAP-Elites.', 'Patrol ablation improved the British side by 18%; a 1,000-game trial produced 238,502 training samples.'],
    link: 'https://github.com/fuxiaoji/wargame',
    tone: 'acid',
  },
  {
    no: '02',
    title: 'AI Lecture Mate',
    subtitle: '实时听课助理',
    enSubtitle: 'Real-time Lecture Assistant',
    period: '2026',
    tags: ['FastAPI', 'WebSocket', 'React', 'Electron', 'faster-whisper'],
    metric: '2× ASR',
    metricLabel: '可切换语音引擎',
    enMetricLabel: 'Switchable speech engines',
    copy: '持续监听课堂、自动识别老师提问，并结合本地课件生成参考答案。它既能作为网页运行，也能打包成常驻桌面的跨平台应用。',
    enCopy: 'Listens to live classes, detects questions and generates course-aware answers as a web or desktop application.',
    details: ['后端使用 Python 3.11、FastAPI、WebSocket；前端采用 React、TypeScript，Electron 负责托盘、快捷键和后端进程管理。', '支持 macOS 系统内置语音与 faster-whisper 离线识别，解决转录漂移、重复字幕和原生依赖打包问题。', '兼容 DeepSeek、OpenAI、MiniMax、Moonshot、智谱与 Qwen，并提供中英日韩多语言识别。'],
    enDetails: ['FastAPI and WebSocket backend, React/TypeScript frontend, with Electron handling tray, shortcuts and process lifecycle.', 'Switches between macOS on-device recognition and offline faster-whisper.', 'Supports six OpenAI-compatible providers and four recognition languages.'],
    link: 'https://github.com/fuxiaoji/ai-class-assistant',
    tone: 'ink',
  },
  {
    no: '03',
    title: 'VibePad',
    subtitle: '系统信号重映射中枢',
    enSubtitle: 'System Input Remapping Hub',
    period: '2026',
    tags: ['Python', 'PyQt6', 'HID', 'pygame', 'YAML'],
    metric: '3 MODES',
    metricLabel: '鼠标 / Vibe / Vim',
    enMetricLabel: 'Mouse / Vibe / Vim',
    copy: '把 Xbox、PS5 或 Switch Pro 手柄变成桌面控制器。覆盖鼠标、滚动、拖拽、快捷键、语音输入与 Vibe Coding 工作流。',
    enCopy: 'Turns Xbox, PS5 or Switch Pro controllers into a desktop interface for mouse, scrolling, macros, voice and Vibe Coding.',
    details: ['hidapi 与 pygame 构成双输入后端，pynput 输出系统级键鼠事件，PyQt6 提供绑定编辑与状态仪表盘。', '长按 LB 进入 Vibe 快捷键层，可接受或拒绝 AI 建议、提交提示、复制粘贴；YAML 支持自定义映射。', '提供无需 Python 的 Windows Release，并处理 UAC 权限、浏览器适配和虚拟键盘调用。'],
    enDetails: ['Dual HID/pygame input backends, pynput system output and a PyQt6 configuration dashboard.', 'A hold-to-enter Vibe layer maps AI coding actions; YAML enables custom bindings.', 'Ships as a standalone Windows release with browser and system-keyboard integration.'],
    link: 'https://github.com/fuxiaoji/VibePad',
    tone: 'coral',
  },
  {
    no: '04',
    title: 'Fama–French Lab',
    subtitle: '三因子模型学术复现',
    enSubtitle: 'Three-factor Research Reproduction',
    period: '2026',
    tags: ['Python', 'Jupyter', 'Econometrics', 'Data Visualization'],
    metric: '312 M',
    metricLabel: '月度观测',
    enMetricLabel: 'Monthly observations',
    copy: '复现 Fama & French 经典三因子论文，并把 2000—2026 年结果与原始时期进行比较，形成可重复的金融计量研究流程。',
    enCopy: 'Reproduces the classic three-factor paper and compares 2000–2026 results with the original period.',
    details: ['覆盖 26 年、312 个月数据，复现 Table 2 与 Table 6，并对 25 个 Size × B/M 投资组合做时间序列回归。', '5 个渐进式 Notebook 与 5 个可复用 Python 模块，代码超过 1,800 行。', '输出 10+ 学术图表，包括累积收益、滚动波动率、Alpha 与调整后 R² 热力图。'],
    enDetails: ['26 years and 312 monthly observations, reproducing Tables 2 and 6 across 25 Size × B/M portfolios.', 'Five notebooks and five reusable Python modules totaling over 1,800 lines.', 'More than ten academic figures covering returns, volatility, alpha and adjusted R².'],
    link: 'https://github.com/fuxiaoji/reprodue_fama_modle',
    tone: 'blue',
  },
  {
    no: '05', title: 'TiebaReaper', subtitle: '贴吧全量归档工具', enSubtitle: 'Complete Tieba Archiver', period: '2026',
    tags: ['Python', 'PyQt6', 'Concurrency', 'Markdown'], metric: '3 LAYERS', metricLabel: '主楼 / 楼层 / 楼中楼', enMetricLabel: 'Post / reply / nested reply',
    copy: '输入帖子链接或 ID，完整抓取正文、楼层、楼中楼与图片，最终输出适合 Obsidian 阅读的本地 Markdown 档案。', enCopy: 'Archives posts, replies, nested replies and images into clean local Markdown for long-term reading.',
    details: ['并发下载多媒体资源，同时保留作者、时间和点赞信息；内置请求间隔以降低封禁风险。', '纯手写 PyQt6 界面提供进度反馈，也提供网页入口和可发布的 OpenClaw Skill。', '输出独立目录与本地图片引用，避免原图床失效导致历史内容丢失。'],
    enDetails: ['Concurrent media downloads preserve author, time and likes with a built-in request delay.', 'A custom PyQt6 interface, web entry and OpenClaw Skill expose the workflow.', 'Self-contained Markdown folders keep archives independent of the original image host.'],
    link: 'https://github.com/fuxiaoji/tieba_spider', tone: 'acid',
  },
  {
    no: '06', title: 'Bidding Data Pipeline', subtitle: '公共资源交易数据抓取器', enSubtitle: 'Public Procurement Data Pipeline', period: '2026',
    tags: ['Python', 'Incremental ETL', 'CSV', 'Excel'], metric: '5 YEARS', metricLabel: '历史数据范围', enMetricLabel: 'Historical data range',
    copy: '面向重庆公共资源交易网的轻量增量采集工具，将分页列表与详情页转成可分析的结构化中标数据。', enCopy: 'An incremental collector that turns procurement listings and detail pages into analysis-ready award data.',
    details: ['自动翻页并逐条解析详情，兼容不同页面标签写法，提取项目名、公开时间、评委名单和详情链接。', '已有历史记录自动跳过，可配置日期、页数、超时与请求间隔，导出 CSV 和 Excel。', '提供 smoke test 与实时完整率，便于先做小范围验证再执行长期采集。'],
    enDetails: ['Automatic pagination and resilient detail parsing across inconsistent labels.', 'Incremental deduplication, configurable limits and CSV/Excel exports.', 'Smoke tests and completeness progress support safe small-batch validation.'],
    link: 'https://github.com/fuxiaoji/crawler_for_biddingprofile', tone: 'ink',
  },
  {
    no: '07', title: 'Quant Rotation Lab', subtitle: 'ETF 动量轮动回测', enSubtitle: 'ETF Momentum Rotation Backtest', period: '2025',
    tags: ['Python', 'AkShare', 'Pandas', 'QuantStats', 'DeepSeek'], metric: '4 METRICS', metricLabel: '收益 / 波动 / 夏普 / 回撤', enMetricLabel: 'Return / vol / Sharpe / drawdown',
    copy: '自动获取 ETF 历史数据，计算涨幅与斜率动量，生成轮动信号，并把策略表现整理成可视化报告。', enCopy: 'Fetches ETF history, scores momentum and slope, generates rotation signals and produces performance reports.',
    details: ['AkShare 负责行情获取与合并，Pandas 和 NumPy 构建信号，QuantStats 输出绩效分析。', '报告覆盖收益率、波动率、夏普比率与最大回撤，并绘制策略净值曲线。', '同时集成 OpenAI SDK 与 DeepSeek 接口，探索 LLM 在研究解释环节的辅助作用。'],
    enDetails: ['AkShare data ingestion with Pandas/NumPy signal construction and QuantStats reporting.', 'Reports return, volatility, Sharpe ratio, maximum drawdown and NAV curves.', 'An OpenAI-compatible DeepSeek interface explores LLM-assisted research interpretation.'],
    link: 'https://github.com/fuxiaoji/quant_test', tone: 'coral',
  },
]

export const capabilities = [
  ['AI SYSTEMS', 'RAG / Agent / MCP / Multi-Agent / PGvector', 'AI 应用系统', '熟悉 Spring AI、LangChain4j 等 AI 开发框架，能够从需求分析与架构设计开始，独立完成企业级智能体应用的开发与交付。', 'Builds enterprise AI agents from requirements and architecture through implementation and delivery with Spring AI and LangChain4j.', ['基于 PGvector 构建 RAG 知识库，贯通文档 ETL、向量检索、查询增强与复杂 Prompt 工程。', '具备工具调用、MCP Server、Agent Skills 与多 Agent 协作应用的开发和发布经验。', '熟悉 SDD、Harness Engineering、Spec-Kit 与 OpenSpec，可驱动 AI 完成大型全栈项目。'], ['Builds PGvector RAG pipelines across document ETL, retrieval, query enhancement and prompt engineering.', 'Develops and publishes tool-calling flows, MCP servers, Agent Skills and multi-agent systems.', 'Uses SDD, Harness Engineering, Spec-Kit and OpenSpec to deliver larger AI-native products.']],
  ['MODEL & GAME', 'PyTorch / Transformer / LSTM / Evolutionary RL', '模型与游戏 AI', '掌握深度学习基础、PyTorch、Transformer 与 LSTM，能独立设计、开发并迭代游戏 AI 与遗传演化强化学习框架。', 'Designs and iterates production game AI and evolutionary reinforcement-learning systems with PyTorch, Transformers and LSTMs.', ['在 Bismarck Hunt 中打通 C++ 训练环境、PyTorch 策略演化与 TypeScript 实时可视化的完整闭环。', '通过变异率、奖励函数与并发采样调优，产出 200+ 不同难度和战术风格的 AI 模型。', '核心 AI 相对基线胜率绝对提升 40%，并支持高并发对局采样与训练监控。'], ['Connected a C++ simulation, PyTorch evolution and TypeScript live visualization in Bismarck Hunt.', 'Produced 200+ difficulty and tactical-style variants by tuning mutation rates, rewards and sampling.', 'Raised baseline win rate by 40% while supporting concurrent matches and training observability.']],
  ['ENGINEERING', 'Python / C++ / TypeScript / Solidity / Stata', '全栈工程', '拥有后端与全栈开发经验，能在高性能计算、Web 产品、链上应用与自动化数据工程之间完成跨栈实现。', 'Works across high-performance systems, web products, on-chain applications and automated data engineering.', ['使用 C++ 构建游戏状态机和小型引擎，使用 TypeScript 完成交互前端与实时数据渲染。', '能独立编写、审计并部署 Solidity 智能合约，完成小型链上应用。', '掌握 Python 异步并发与反爬策略，实现复杂嵌套网页和多媒体资源的全量采集、清洗与结构化导出。'], ['Builds C++ state machines and compact engines alongside TypeScript interfaces and real-time visualization.', 'Writes, audits and deploys Solidity contracts for small on-chain products.', 'Uses asynchronous Python and anti-blocking strategies for full extraction, cleaning and structured export.']],
  ['3D & INTERACTIVE', 'UE5 / Unity / Blender / Shader / Animation', '三维与交互', '掌握 UE5 蓝图/C++、Unity 与 Blender，可独立完成从三维资产到可运行交互体验的制作流程。', 'Creates complete interactive experiences with UE5 Blueprint/C++, Unity and Blender.', ['能够完成场景建模、UV 与贴图、灯光布置、材质和 Shader 编写。', '具备镜头设计、场景拍摄与动画制作能力，可开发小型游戏原型。', '关注交互反馈、状态可视化和复杂系统的信息呈现，而不只停留在静态建模。'], ['Handles modeling, UVs, texturing, lighting, materials and shader development.', 'Designs cameras, captures scenes and produces animation for compact game prototypes.', 'Focuses on interaction feedback and complex-system visualization beyond static assets.']],
  ['RESEARCH', 'Wind / Choice / Financial Modeling / Data Mining / SEO / GEO', '研究与数据', '金融学训练与工程能力并行，熟悉宏观周期、证券市场运行逻辑、基金交易机制和完整的数据研究流程。', 'Combines finance training with engineering across macro cycles, markets, fund workflows and end-to-end data research.', ['熟练使用 Wind、Choice，能够执行海外宏观信息挖掘、收集、清洗，并完成专题研究报告。', '具备 MCM/ICM 建模经验，可独立贯通数据获取、特征工程、预测建模、回测验证和可视化。', '掌握 SEO 与 GEO，可通过结构化内容和 TDK 优化提升搜索收录与生成式推荐表现。'], ['Uses Wind and Choice for overseas macro research, data collection, cleaning and thematic reporting.', 'Applies MCM/ICM modeling experience across acquisition, features, prediction, backtesting and visualization.', 'Improves search and generative discovery through structured content, TDK, SEO and GEO.']],
]

export const facts = [
  ['2024—2028', '西南财经大学 · 金融学（经管国际化创新实验班）', 'SWUFE · Finance, International Innovation Program'],
  ['GPA 3.3/4', '专业前 30% · 双奖学金', 'Top 30% · Two scholarships'],
  ['2025', '中泰证券深圳分部 · 行研与基金服务', 'Zhongtai Securities · Research & Fund Services'],
  ['5+ REPOS', '持续维护的独立开源项目', 'Independently maintained open-source projects'],
]

export const awards = [
  ['全国前 2%', '第三届全国 ETF 模拟投资挑战赛 · 二等奖', 'National ETF Challenge · Second Prize'],
  ['前 10%', '西南财经大学金融科技建模大赛 · 二等奖', 'SWUFE FinTech Modeling · Top 10%'],
  ['+6%', '三个月 ETF 模拟实盘收益率', 'Three-month simulated ETF return'],
  ['2,300+ H', '《战地》系列体验与系统观察', 'Battlefield play and systems observation'],
]

export const photographs = [
  ['078b88b66a8b2f1bab00e072ffdf7fe0.jpg', 'FIELD / 01'],
  ['19fe9711f293690d0f284f205ef2e987.jpg', 'FIELD / 02'],
  ['25c4d98036115c98f231c62d90005970.jpeg', 'FIELD / 03'],
  ['8562470192cf76943e9acf21df4fd607.jpg', 'FIELD / 04'],
  ['8d1acd0f8314c9a56308436e2af3702d.jpg', 'FIELD / 05'],
  ['IMG_2874.jpeg', 'FIELD / 06'],
  ['IMG_3421.jpeg', 'FIELD / 07'],
  ['IMG_3893.jpeg', 'FIELD / 08'],
  ['IMG_4098.jpeg', 'FIELD / 09'],
  ['IMG_4212.jpeg', 'FIELD / 10'],
  ['IMG_4984.JPG', 'FIELD / 11'],
  ['d8548023ca6e0f529fa56d584ad7b6dd.jpg', 'FIELD / 12'],
]
