export const projects = [
  {
    no: '01',
    title: 'Bismarck Hunt',
    subtitle: '兵棋 AI 演化框架',
    enSubtitle: 'Evolutionary Wargame AI',
    period: '2026',
    tags: ['C++', 'PyTorch', 'TypeScript', 'Evolutionary RL'],
    metric: '+40%',
    metricLabel: 'AI 基线胜率',
    enMetricLabel: 'AI baseline win rate',
    copy: '把《追击俾斯麦》做成可训练的数字战场。C++ 并发采样，PyTorch 演化策略，TypeScript 实时看见每次进化。',
    enCopy: 'A trainable digital battlefield: concurrent C++ sampling, evolutionary PyTorch policies and real-time TypeScript visualization.',
    link: 'https://github.com/fuxiaoji/wargame',
    tone: 'acid',
  },
  {
    no: '02',
    title: 'AI Lecture Mate',
    subtitle: '实时听课助理',
    enSubtitle: 'Real-time Lecture Assistant',
    period: '2026',
    tags: ['Audio Stream', 'LLM', 'RAG', 'Agent'],
    metric: 'LIVE',
    metricLabel: '语音流增强回答',
    enMetricLabel: 'Streaming contextual answers',
    copy: '持续监听课堂音频，识别问题意图，再从本地课件中找到上下文。让“没听懂”立刻变成一次可追问的对话。',
    enCopy: 'Listens to live class audio, detects questions and retrieves context from local courseware for answers you can keep exploring.',
    link: 'https://github.com/fuxiaoji',
    tone: 'ink',
  },
  {
    no: '03',
    title: 'VibePad',
    subtitle: '系统信号重映射中枢',
    enSubtitle: 'System Input Remapping Hub',
    period: '2026',
    tags: ['Input Mapping', 'Desktop', 'Open Source'],
    metric: '01→∞',
    metricLabel: '手柄到系统指令',
    enMetricLabel: 'Controller to system command',
    copy: '把物理手柄重映射为键鼠流与组合宏。它不是按键替换器，更像一套给桌面操作准备的乐器接口。',
    enCopy: 'Maps a physical controller to keyboard, mouse and compound macros—more like an instrument interface for desktop control.',
    link: 'https://github.com/fuxiaoji',
    tone: 'coral',
  },
  {
    no: '04',
    title: 'Data Crawlers',
    subtitle: '复杂网页采集工具组',
    enSubtitle: 'Complex Web Data Toolkit',
    period: '2025—26',
    tags: ['Python', 'Async IO', 'Data Pipeline'],
    metric: 'FULL',
    metricLabel: '历史数据结构化',
    enMetricLabel: 'Structured historical data',
    copy: '面向政务招投标与复杂嵌套社区，处理增量抓取、异步并发、多媒体资源和反爬策略。脏活，也要做得漂亮。',
    enCopy: 'Incremental collection, async concurrency, media assets and anti-bot strategies for public procurement and nested communities.',
    link: 'https://github.com/fuxiaoji/crawler_for_biddingprofile',
    tone: 'blue',
  },
]

export const capabilities = [
  ['AI SYSTEMS', 'RAG / Agent / MCP / Multi-Agent / PGvector', 'AI 应用系统'],
  ['MODEL & GAME', 'PyTorch / Transformer / LSTM / Evolutionary RL', '模型与游戏 AI'],
  ['ENGINEERING', 'Python / C++ / TypeScript / Solidity / Stata', '全栈工程'],
  ['3D & INTERACTIVE', 'UE5 / Unity / Blender / Shader / Animation', '三维与交互'],
  ['RESEARCH', 'Financial Modeling / Data Mining / SEO / GEO', '研究与数据'],
]

export const facts = [
  ['2024—2028', '西南财经大学 · 金融学（经管国际化创新实验班）', 'SWUFE · Finance, International Innovation Program'],
  ['GPA 3.3/4', '专业前 30% · 双奖学金', 'Top 30% · Two scholarships'],
  ['2025', '中泰证券深圳分部 · 行研与基金服务', 'Zhongtai Securities · Research & Fund Services'],
  ['5+ REPOS', '持续维护的独立开源项目', 'Independently maintained open-source projects'],
]

export const awards = [
  ['全国前 2%', '第三届全国 ETF 模拟投资挑战赛 · 二等奖', 'National ETF Challenge · Second Prize'],
  ['前 10%', '西南财经大学金融科技建模大赛 · 二等奖', 'SWUFE FinTech Modeling · Top 10%'],
  ['+6%', '三个月 ETF 模拟实盘收益率', 'Three-month simulated ETF return'],
  ['2,300+ H', '《战地》系列体验与系统观察', 'Battlefield play and systems observation'],
]

export const photographs = [
  ['078b88b66a8b2f1bab00e072ffdf7fe0.jpg', 'FIELD / 01'],
  ['19fe9711f293690d0f284f205ef2e987.jpg', 'FIELD / 02'],
  ['25c4d98036115c98f231c62d90005970.jpeg', 'FIELD / 03'],
  ['8562470192cf76943e9acf21df4fd607.jpg', 'FIELD / 04'],
  ['8d1acd0f8314c9a56308436e2af3702d.jpg', 'FIELD / 05'],
  ['IMG_2874.jpeg', 'FIELD / 06'],
  ['IMG_3421.jpeg', 'FIELD / 07'],
  ['IMG_3893.jpeg', 'FIELD / 08'],
  ['IMG_4098.jpeg', 'FIELD / 09'],
  ['IMG_4212.jpeg', 'FIELD / 10'],
  ['IMG_4984.JPG', 'FIELD / 11'],
  ['d8548023ca6e0f529fa56d584ad7b6dd.jpg', 'FIELD / 12'],
]
